### ISSUE TITLE
Use failure_message instead of failure_message_for_should

### ISSUE THREAD

**Issue by jonathandean** [stitchfix/stitches#10]
To fix deprecation warnings:

- [ ] https://github.com/stitchfix/stitches/blob/9aab95d0ddd1cb0b0258961707ca203da6128882/lib/stitches/spec/be_iso_8601_utc_encoded.rb
- [ ] https://github.com/stitchfix/stitches/blob/9aab95d0ddd1cb0b0258961707ca203da6128882/lib/stitches/generator_files/spec/features/api_spec.rb#L83

**Comment by davetron5000** [comment]
This got done.  I think by @simeonwillbanks !
