### ISSUE TITLE
Failure message on fresh install and rspec run. 

### ISSUE THREAD

**Issue by iCreateJB** [stitchfix/stitches#17]
rails new APP_NAME
 - added gem 'stitches'
rails g rspec:install
rails g apitome:install
rails g stitches:api
 - create database
 - run migrations
 - run rspec to validate setup

[error]
uninitialized constant RSpec::Rails (NameError)

**Comment by davetron5000** [comment]
Were you able to do anything manually to fix this for your local install? i.e. is there a gem missing we need to add as a dependency?  If not, could you post a fuller stack trace?

**Comment by iCreateJB** [comment]
./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core.rb:178:in `block in const_missing': uninitialized constant RSpec::Rails (NameError)
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core.rb:178:in `fetch'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core.rb:178:in `const_missing'
	from ./workspace/github/honorable/spec/spec_helper.rb:94:in `block in <top (required)>'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core.rb:97:in `configure'
	from ./workspace/github/honorable/spec/spec_helper.rb:20:in `<top (required)>'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration.rb:1295:in `require'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration.rb:1295:in `each'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration.rb:1295:in `requires='
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration_options.rb:108:in `each'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/configuration_options.rb:21:in `configure'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:101:in `setup'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:88:in `run'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:73:in `run'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/lib/rspec/core/runner.rb:41:in `invoke'
	from ./.rvm/gems/ruby-2.2.2/gems/rspec-core-3.4.0/exe/rspec:4:in `<top (required)>'
	from ./.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from ./.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from ./.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from ./.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by davetron5000** [comment]
Still looking, but it appears that stitches is putting things in `spec_helper.rb` that should go in `rails_helper.rb`.  Unfortunately, doing that created new problems.

**Comment by davetron5000** [comment]
Can you try again using the branch?

```ruby
# Gemfile

gem 'stitches', github: 'stitchfix/stitches', branch: 'fix-generator-issues'
```

**Comment by iCreateJB** [comment]
This worked. 

I ran into an install error; missing responders gem. 

I submitted a PR for it. 

Thanks
