### ISSUE TITLE
License missing. MIT?

### ISSUE THREAD

**Issue by bf4** [stitchfix/stitches#5]
(missing from repo and gemspec)

**Comment by jonathandean** [comment]
Thanks @bf4 ! I'll add an MIT license today, I think that's what we use elsewhere: https://github.com/stitchfix/immutable-struct/blob/master/LICENSE.txt

**Comment by bf4** [comment]
It's one of the more common ones. See https://github.com/rubygems/rubygems/pull/1249

**Comment by bf4** [comment]
FWIW, though this isn't full baked, I've set up a basic re-usable gem template based on bundler's that behaves like Rails templates... https://github.com/bf4/gemnerator

**Comment by jonathandean** [comment]
Thanks for the link, @bf4 I will take a look :)

I think the gap here is that this gem was generated by an internal generator similar to that one and we converted it to open source after having used it a while. We obviously don't need an open source license for non open source code, so I just missed that when converting it over.
