### ISSUE TITLE
Uninitialized constant Api::V1 in debug

### ISSUE THREAD

**Issue by viktorianer** [stitchfix/stitches#86]
**Problem**:
I get `ActionController::RoutingError (uninitialized constant Api::V1)` in debug mode using Fast Debugger in IntelliJ IDEA (`ruby-debug-ide` 0.8.0.beta8 with `debase` 0.3.0.beta8).

**Steps to reproduce**:

Create new Rails 6 API app [and setup stitches](https://github.com/stitchfix/stitches/wiki/Setup).

Create a `Controller`, e.g. `RestaurantsController` with Rails scaffold:

My example rails app has following routes then:
```
namespace :api do
    scope module: :v1, constraints: Stitches::ApiVersionConstraint.new(1) do
      resource :ping, only: [:create]
      # Add your V1 resources here
      resources :restaurants
    end
  end
end
...
```
Controller looks like:
```
class Api::V1::RestaurantsController < Api::ApiController
...
  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      render json: { restaurant: @restaurant }, status: :created,
             location: @restaurant
    else
      render json: Stitches::Errors.from_active_record(@restaurant),
             status: :unprocessable_entity
    end
  end
...
end
```

Now start Server with `rails s` and send proper POST `to localhost:3000/api/restaurants/1`.
It works just fine for now.

Now start Server with [debug](https://github.com/ruby-debug/ruby-debug-ide) and you will see the error: `ActionController::RoutingError (uninitialized constant Api::V1)` with the same POST request.

**Comment by bwebster** [comment]
@viktorianer Thanks for posting this.  After doing some research, it looks like this is a [known issue for the current version of RubyMine](https://youtrack.jetbrains.com/issue/RUBY-24781?_ga=2.243265410.1680375377.1571673280-1649389073.1551582207).  I was able to reproduce this with RubyMine v2019.2.3.  Installing a EAP version of RubyMine seemed to fix the issue.

Given that, I believe the root issue is in either the `ruby-debug-ide` or `debase` gem.

**Comment by viktorianer** [comment]
Oh, sorry for that. I had no time to do research on this. Thank you a lot.

**Comment by bwebster** [comment]
Not a problem!
