### ISSUE TITLE
Use expect instead of should syntax for all specs given by generator

### ISSUE THREAD

**Issue by jonathandean** [stitchfix/stitches#9]
For example: https://github.com/stitchfix/stitches/blob/9aab95d0ddd1cb0b0258961707ca203da6128882/lib/stitches/generator_files/spec/acceptance/ping_v1_spec.rb#L20

**Comment by davetron5000** [comment]
Looks like this was fixed soon after in 84969ebc544a64eea7190cf5b7604da79e1d476b
